# Projeto 1 - Ciência dos Dados

Nome: _____

Nome: _____

Atenção: Serão permitidos grupos de três pessoas, mas com uma rubrica mais exigente. Grupos deste tamanho precisarão fazer um questionário de avaliação de trabalho em equipe

___
Carregando algumas bibliotecas:

In [1]:
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os

In [2]:
print('Esperamos trabalhar no diretório')
print(os.getcwd())

Esperamos trabalhar no diretório
C:\Users\caioj\OneDrive - Insper - Institudo de Ensino e Pesquisa\2 semestre\C. Dados\projeto 1

Carregando a base de dados com os tweets classificados manualmente:

In [3]:
train = pd.read_excel('dados_treino.xlsx')
train.head(5)

,Mensagem,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 87,Unnamed: 88,Unnamed: 89,Unnamed: 90,Unnamed: 91,Unnamed: 92,Unnamed: 93,Unnamed: 94,Unnamed: 95,Target
0,Um dos livros faltam mais de 40 páginas. Ex.: ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,entrega
1,"O livro é incompleto. Acaba em 11/04/44, sendo...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,entrega
2,"Ainda não terminei, estou nos 40%, devo ler em...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,conteúdo
3,Pedi o livro baseado na promoção q era de graç...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,entrega
4,"Prezados, Acredito que houve um erro, pois des...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,entrega

In [4]:
test = pd.read_excel('dados_teste.xlsx')
test.head(5)

,Mensagem,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Target
0,a narrativa é muito lenta e você fica ansioso ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,conteúdo
1,Sim.adorei o livro Vou continuar a comprar o r...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,conteúdo
2,"Desculpem, mas achei deprimente e não me ensin...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,conteúdo
3,Preciso saber se essa compra é do livro físico...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,entrega
4,"Embora tenha gostado do livro ""Não Faz Sentido...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,conteúdo

___
## Classificador automático

Faça aqui uma descrição do seu assunto e o que considerou como relevante ou não relevante na classificação dos tweets (Target).

ESCREVA AQUI...

___
### Montando um Classificador Naive-Bayes

Considerando apenas as mensagens da planilha Treinamento, ensine  seu classificador.

In [64]:
df_train = train['Mensagem'].to_frame()
df_train['Target'] = train['Target']

df_test = test['Mensagem'].to_frame()
df_test['Target'] = test['Target']

In [68]:
caracteres = [':',',','.','(',')', '?', '!', '"']
i = 0
for msg in df_train.Mensagem:
    for caractere in caracteres:
        if caractere in msg:
            msg = msg.replace(caractere, '')
            msg = msg.lower()
    df_train.loc[i, 'Mensagem'] = msg 
    i += 1
    
    
j = 0
for msg in df_test.Mensagem:
    for caractere in caracteres:
        if caractere in msg:
            msg = msg.replace(caractere, '')
            msg = msg.lower()
    df_test.loc[j, 'Mensagem'] = msg 
    j += 1

In [69]:
df_train.head(5)

                                            Mensagem    Target
0  um dos livros faltam mais de 40 páginas ex pul...   entrega
1  o livro é incompleto acaba em 11/04/44 sendo q...   entrega
2  ainda não terminei estou nos 40% devo ler em m...  conteúdo
3  pedi o livro baseado na promoção q era de graç...   entrega
4  prezados acredito que houve um erro pois desco...   entrega

In [70]:
df_test.head(5)

                                            Mensagem    Target
0  a narrativa é muito lenta e você fica ansioso ...  conteúdo
1  simadorei o livro vou continuar a comprar o re...  conteúdo
2  desculpem mas achei deprimente e não me ensino...  conteúdo
3  preciso saber se essa compra é do livro físico...   entrega
4  embora tenha gostado do livro não faz sentido ...  conteúdo

___
### Verificando a performance do Classificador

Agora você deve testar o seu classificador com a base de Testes.

___
### Concluindo

___
### Qualidade do Classificador a partir de novas separações dos tweets entre Treinamento e Teste

Caso for fazer esse item do Projeto

___
## Aperfeiçoamento:

Trabalhos que conseguirem pelo menos conceito B vão evoluir em conceito dependendo da quantidade de itens avançados:

* IMPLEMENTOU outras limpezas e transformações que não afetem a qualidade da informação contida nos tweets. Ex: stemming, lemmatization, stopwords
* CONSIDEROU mais de duas categorias na variável Target e INCREMENTOU a quantidade de notícias, mantendo pelo menos 250 notícias por categoria (OBRIGATÓRIO PARA TRIOS, sem contar como item avançado)
* Para Target com duas categorias: CRIOU pelo menos quatro categorias intermediárias de relevância baseadas na probabilidade: ex.: muito relevante, relevante, neutro, irrelevante, muito irrelevante
* EXPLICOU porquê não pode usar o próprio classificador para gerar mais amostras de treinamento
* PROPÔS diferentes cenários para Naïve Bayes fora do contexto do projeto (pelo menos dois cenários, exceto aqueles já apresentados em sala pelos professores: por exemplo, filtro de spam)
* SUGERIU e EXPLICOU melhorias reais com indicações concretas de como implementar (indicar como fazer e indicar material de pesquisa)
* FEZ o item Qualidade do Classificador a partir de novas separações das Notícias entre Treinamento e Teste descrito no enunciado do projeto (OBRIGATÓRIO para conceitos A ou A+)

___
## Referências

[Naive Bayes and Text Classification](https://arxiv.org/pdf/1410.5329.pdf)  **Mais completo**

[A practical explanation of a Naive Bayes Classifier](https://monkeylearn.com/blog/practical-explanation-naive-bayes-classifier/) **Mais simples**